[build]
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://skidrc-store.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/healthz"
  to = "https://skidrc-store.onrender.com/healthz"
  status = 200


